export const mockAttendance = [
  {
    id: "a1",
    employeeId: "e1",
    employeeName: "Aarav Mehta",
    department: "Finance",
    manager: "Sara Khan",
    date: "02-Sep-2026",
    checkIn: "02-Sep-2026 09:05",
    checkOut: "02-Sep-2026 18:10",
    workedHours: 9.08,
    overtime: 0.5,
    status: "present",
    notes: "System-generated from check in/out or manually corrected by an authorized user.",
  },
  {
    id: "a2",
    employeeId: "e2",
    employeeName: "Sara Khan",
    department: "HR",
    manager: "Maya Shah",
    date: "02-Sep-2026",
    checkIn: "02-Sep-2026 09:15",
    checkOut: "02-Sep-2026 18:02",
    workedHours: 8.78,
    overtime: 0.2,
    status: "present",
    notes: "System-generated from check in/out or manually corrected by an authorized user.",
  },
  {
    id: "a3",
    employeeId: "e3",
    employeeName: "John Dsouza",
    department: "Engineering",
    manager: "Nisha Rao",
    date: "02-Sep-2026",
    checkIn: "02-Sep-2026 09:22",
    checkOut: "02-Sep-2026 17:58",
    workedHours: 8.43,
    overtime: 0,
    status: "present",
    notes: "System-generated from check in/out or manually corrected by an authorized user.",
  },
  {
    id: "a4",
    employeeId: "e4",
    employeeName: "Neha Patel",
    department: "HR",
    manager: "Maya Shah",
    date: "02-Sep-2026",
    checkIn: null,
    checkOut: null,
    workedHours: 0,
    overtime: 0,
    status: "absent",
    notes: "No check-in recorded for this date.",
  },
];

// Reference "today" for the mock dataset — real backend would use the actual date.
export const MOCK_TODAY = "02-Sep-2026";