export const mockContracts = [
  {
    id: "c1",
    contractNumber: "CON/2026/004",
    employeeName: "Aarav Mehta",
    department: "Finance",
    jobPosition: "Payroll Specialist",
    startDate: "01-Jan-26",
    endDate: null,
    wageMonth: 85000,
    status: "running",
    workingSchedule: "40 Hours / Week",
    notes: "Structure Type: Employee Salary. This running contract is the source for payroll calculation in the active period.",
  },
  {
    id: "c2",
    contractNumber: "CON/2025/001",
    employeeName: "Aarav Mehta",
    department: "Finance",
    jobPosition: "Payroll Specialist",
    startDate: "01-Jul-25",
    endDate: "31-Dec-25",
    wageMonth: 78000,
    status: "expired",
    workingSchedule: "40 Hours / Week",
    notes: "Previous contract period — no longer used for payroll.",
  },
  {
    id: "c3",
    contractNumber: "CON/2026/003",
    employeeName: "Sara Khan",
    department: "HR",
    jobPosition: "HR Officer",
    startDate: "01-Jan-26",
    endDate: null,
    wageMonth: 95000,
    status: "running",
    workingSchedule: "40 Hours / Week",
    notes: "Structure Type: Employee Salary. This running contract is the source for payroll calculation in the active period.",
  },
];