export const mockTimeOffRequests = [
  {
    id: "r1",
    employeeName: "Aarav Mehta",
    typeName: "Paid Time Off",
    startDate: "12-Sep",
    endDate: "14-Sep",
    duration: "3 Days",
    status: "approved",
    approver: "Sara Khan",
    allocationUsed: "Paid Time Off 2026",
    reason: "Family vacation",
  },
  {
    id: "r2",
    employeeName: "Sara Khan",
    typeName: "Sick Leave",
    startDate: "18-Sep",
    endDate: "18-Sep",
    duration: "1 Day",
    status: "approved",
    approver: "Maya Shah",
    allocationUsed: null,
    reason: "Not feeling well.",
  },
  {
    id: "r3",
    employeeName: "John Dsouza",
    typeName: "Comp Off",
    startDate: "27-Sep",
    endDate: "27-Sep",
    duration: "1 Day",
    status: "to_approve",
    approver: "Nisha Rao",
    allocationUsed: "Comp Off 2026",
    reason: "Compensatory day off for weekend deployment work.",
  },
];