export const mockTimeOffTypes = [
  {
    id: "t1",
    typeName: "Paid Time Off",
    unit: "Days",
    requiresAllocation: true,
    approval: "Manager",
    active: true,
    payrollWorkEntry: "Leave Work Entry",
    displayColor: "Blue",
    notes: "Standard annual leave. Balance comes from approved allocations.",
  },
  {
    id: "t2",
    typeName: "Sick Leave",
    unit: "Days",
    requiresAllocation: false,
    approval: "Manager",
    active: true,
    payrollWorkEntry: "Leave Work Entry",
    displayColor: "Amber",
    notes: "No allocation required — approval alone grants the leave.",
  },
  {
    id: "t3",
    typeName: "Comp Off",
    unit: "Hours",
    requiresAllocation: true,
    approval: "Officer",
    active: true,
    payrollWorkEntry: "Leave Work Entry",
    displayColor: "Green",
    notes: "Compensatory off earned from extra hours worked; requires an allocation to draw from.",
  },
];