export const mockAllocations = [
  {
    id: "al1",
    employeeName: "Aarav Mehta",
    typeName: "Paid Time Off",
    allocated: 20,
    taken: 8,
    remaining: 12,
    status: "approved",
    approver: "Sara Khan",
    validity: "2026 Annual Balance",
    description: "Annual leave balance granted at start of policy year.",
  },
  {
    id: "al2",
    employeeName: "Sara Khan",
    typeName: "Paid Time Off",
    allocated: 18,
    taken: 4,
    remaining: 14,
    status: "approved",
    approver: "Maya Shah",
    validity: "2026 Annual Balance",
    description: "Annual leave balance granted at start of policy year.",
  },
  {
    id: "al3",
    employeeName: "Neha Patel",
    typeName: "Comp Off",
    allocated: 2,
    taken: 1,
    remaining: 1,
    status: "to_approve",
    approver: "Maya Shah",
    validity: "2026 Comp Balance",
    description: "Comp off earned from extra hours worked, pending approval.",
  },
];